apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwc-share
  labels:
    storage: gwc-datadir
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/geoserver/gwc
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwc-share
spec:
  volumeName: gwc-share
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      storage: "gwc-datadir"