apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gwc"
  labels:
    app: "gwc"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gwc"
  template:
    metadata:
      labels:
        app: "gwc"
        environment: "production"
        tier: "geoserver"
        monitoringActuator: enabled
    spec:
      # securityContext:
        # runAsUser: 1001
        # runAsGroup: 1001
        # fsGroup: 1001
      containers:
      - name: gwc
        image: geoservercloud/geoserver-cloud-gwc:2.27.1.0
        ports:
         - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 50
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 50
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "50m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: 1
        env:
            - name: GEOSERVER_DATA_DIR
              value: "/opt/app/data_directory"
            - name: GEOWEBCACHE_CACHE_DIR
              value: "/data/geowebcache"
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
        volumeMounts:
          - name: shared-data-directory
            mountPath: "/opt/app/data_directory"
          - name: geowebcache-data
            mountPath: "/data/geowebcache"
      restartPolicy: Always
      volumes:
        - name: shared-data-directory
          persistentVolumeClaim:
            claimName: geoserver-pvc
        - name: geowebcache-data
          persistentVolumeClaim:
            claimName: gwc-share
---
apiVersion: v1
kind: Service
metadata:
  name: gwc
  labels:
    app: gwc
spec:
  ports:
  - name: health
    port: 8081
    targetPort: 8081
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: gwc
  type: ClusterIP
