{{- $admin := .Values.services.admin }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "admin"
  labels:
    app: "admin"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "admin"
  template:
    metadata:
      labels:
        app: "admin"
        environment: "production"
        tier: "geoserver"
    spec:
      # securityContext:
        # runAsUser: 1001
        # runAsGroup: 1001
        # fsGroup: 1001
      containers:
        - name: "admin"          
          image: geoservercloud/geoserver-cloud-admin-server:2.27.1.0
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: "admin"
