apiVersion: apps/v1
kind: Deployment
metadata:
  name: "wfs"
  labels:
    app: "wfs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wfs"
  template:
    metadata:
      labels:
        app: "wfs"
        environment: "production"
        tier: "geoserver"
        monitoringActuator: enabled
    spec:
      # securityContext:
        # runAsUser: 1001
        # runAsGroup: 1001
        # fsGroup: 1001
      containers:
        - name: wfs
          image: geoservercloud/geoserver-cloud-wfs:2.27.1.0
          ports:
          - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 50
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 50
          env:
            - name: GEOSERVER_DATA_DIR
              value: "/opt/app/data_directory"
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
          volumeMounts:
            - name: shared-data-directory
              mountPath: "/opt/app/data_directory"
      restartPolicy: Always
      volumes:
        - name: shared-data-directory
          persistentVolumeClaim:
            claimName: geoserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wfs
  labels:
    app: wfs
spec:
  ports:
  - name: health
    port: 8081
    targetPort: 8081
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: wfs
  type: ClusterIP

