{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- $isStateful := (include "GeoserverCloud.isStatefulService" $name) | trim | eq "true" }}
---
apiVersion: apps/v1
kind: {{ ternary "StatefulSet" "Deployment" $isStateful }}
metadata:
  name: {{ $name }}
  labels:
    {{- include "GeoserverCloud.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  {{- if $isStateful }}
  serviceName: {{ $name }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "GeoserverCloud.labels" $ | nindent 8 }}
        app.kubernetes.io/name: {{ $name }}
    spec:
      {{- include "GeoserverCloud.imagePullSecrets" (dict "svc" $svc "global" $.Values.global) | nindent 6 }}
      {{- include "GeoserverCloud.podSpecExtras" (dict "svc" $svc "global" $.Values.global) | nindent 6 }}
      containers:
        - name: {{ $name }}
          image: {{ include "GeoserverCloud.image.full" (dict "svc" $svc "Values" $.Values) }}
          imagePullPolicy: {{ include "GeoserverCloud.image.pullPolicy" (dict "svc" $svc "Values" $.Values) }}
          ports:
            - containerPort: {{ $svc.service.containerPort }}
          {{- with (include "GeoserverCloud.allEnv" (dict "svc" $svc "Values" $.Values "Release" $.Release)) }}
          env:
          {{ . | nindent 12 }}
          {{- end }}
          resources: {{- toYaml $svc.resources | nindent 12 }}
          {{- with $svc.readinessProbe }}
          readinessProbe: 
          {{ include "GeoserverCloud.probe" (dict "probe" . "svc" $svc) | nindent 12 }}
          {{- end }}
          {{- with $svc.livenessProbe }}
          livenessProbe:
          {{ include "GeoserverCloud.probe" (dict "probe" . "svc" $svc) | nindent 12 }}
          {{- end }}
          {{- with $svc.startupProbe }}
          startupProbe: 
          {{ include "GeoserverCloud.probe" (dict "probe" . "svc" $svc) | nindent 12 }}
          {{- end }}
          {{- with (include "GeoserverCloud.securityContext" (dict "svc" $svc "Values" $.Values)) }}
          securityContext: {{ . | nindent 12 }}
          {{- end }}
          {{- with $svc.volumeMounts }}
          volumeMounts: 
            {{- include "GeoserverCloud.volumeMounts" (dict "svc" $svc) | nindent 12 }}
          {{- end }}
      {{- with $svc.volumes }}
      volumes: 
        {{- include "GeoserverCloud.volumes" (dict "svc" $svc "root" $.Values) | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}