apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserver-pv
  labels:
    storage: nfs-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/geoserver/data
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
spec:
  volumeName: geoserver-pv
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      storage: "nfs-data"