{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.hpa.enabled }}
{{- $isStateful := (include "GeoserverCloud.isStatefulService" $name) | trim | eq "true" }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ ternary "StatefulSet" "Deployment" $isStateful }}
    name: {{ $name }}
  minReplicas: {{ $svc.hpa.minReplicas | default 1 }}
  maxReplicas: {{ $svc.hpa.maxReplicas | default 3 }}
  metrics:
    {{- $metrics := $svc.hpa.metrics | default list }}
    {{- if eq (len $metrics) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    {{- else }}
    {{- range $metric := $metrics }}
    - type: {{ $metric.type }}
      {{- if eq $metric.type "Resource" }}
      resource:
        name: {{ $metric.resource.name }}
        target:
          type: {{ $metric.resource.target.type }}
          {{- if eq $metric.resource.target.type "Utilization" }}
          averageUtilization: {{ $metric.resource.target.averageUtilization }}
          {{- else if eq $metric.resource.target.type "Value" }}
          averageValue: {{ $metric.resource.target.averageValue }}
          {{- end }}
      {{- else if eq $metric.type "Pods" }}
      pods:
        metric:
          name: {{ $metric.pods.metric.name }}
        target:
          type: {{ $metric.pods.target.type }}
          averageValue: {{ $metric.pods.target.averageValue }}
      {{- else if eq $metric.type "External" }}
      external:
        metric:
          name: {{ $metric.external.metric.name }}
        target:
          type: {{ $metric.external.target.type }}
          {{- if $metric.external.target.value }}
          value: {{ $metric.external.target.value }}
          {{- else if $metric.external.target.averageValue }}
          averageValue: {{ $metric.external.target.averageValue }}
          {{- else if $metric.external.target.averageUtilization }}
          averageUtilization: {{ $metric.external.target.averageUtilization }}
          {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
