{{- range $pvcName, $pvc := .Values.persistentVolumeClaims }}
{{- if $pvc.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.claimName }}
  labels:
    app: {{ $pvcName }}
spec:
  accessModes:
    {{- toYaml $pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  {{- if $pvc.storageClassName }}
  storageClassName: {{ $pvc.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}