{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "GeoserverCloud.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  selector:
    {{- include "GeoserverCloud.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.service.containerPort }}
      targetPort: {{ $svc.service.containerPort }}
    {{- with $svc.service.healthPort}}
    {{- if ne $svc.service.healthPort $svc.service.containerPort }}
    - name: health
      port: {{ $svc.service.healthPort }}
      targetPort: {{ $svc.service.healthPort }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
