apiVersion: apps/v1
kind: Deployment
metadata:
  name: "wms"
  labels:
    app: "wms"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wms"
  template:
    metadata:
      labels:
        app: "wms"
        environment: "production"
        tier: "geoserver"
        monitoringActuator: enabled
    spec:
      # securityContext:
        # runAsUser: 1001
        # runAsGroup: 1001
        # fsGroup: 1001
      containers:
        - name: wms
          image: geoservercloud/geoserver-cloud-wms:2.27.1.0
          ports:
          - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 50
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 50
          env:
            - name: GEOSERVER_DATA_DIR
              value: "/opt/app/data_directory"
            - name: GEOWEBCACHE_CACHE_DIR
              value: "/data/geowebcache"
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
          volumeMounts:
            - name: shared-data-directory
              mountPath: "/opt/app/data_directory"
            - name: geowebcache-data
              mountPath: "/data/geowebcache"
      restartPolicy: Always
      volumes:
        - name: shared-data-directory
          persistentVolumeClaim:
            claimName: geoserver-pvc
        - name: geowebcache-data
          persistentVolumeClaim:
            claimName: gwc-share
---
apiVersion: v1
kind: Service
metadata:
  name: wms
  labels:
    app: wms
spec:
  ports:
  - name: health
    port: 8081
    targetPort: 8081
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: wms
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wms-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wms
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70